tools:
  jdk: 8
  maven: 3.5.0
  


triggers:
  - manual: Run default
flows:
  default:
    - call: versionsCheck
    - call: build

  pr:
    - echo "Running build for $GITHUB_PR_URL"
    - call: versionsCheck
    - (name Maven build) mvn -B clean install

  versionsCheck:
    - (name JDK Version) java -version
    - (name Maven version) mvn -v

  build:
   - exposeVars(maven)
   - (name Project information) echo "Building ${MAVEN_GROUP_ID}:${MAVEN_ARTIFACT_ID}:${MAVEN_VERSION}"
   - (name Maven deploy) mvn -B clean deploy

  release:
    - call: versionsCheck
    - (name Maven release) mvn -B clean release:prepare release:perform
  
  snapshotDeploy:
    - exposeVars(maven)
    - call: build
    - echo " Snapshot Deploy to Oneops ${MAVEN_VERSION} "
    - oneops.transitionVariableUpdate(platform = '${platform}', component = artifact-app, variables = {artifactId = '${MAVEN_ARTIFACT_ID}', groupId='${MAVEN_GROUP_ID}' , appVersion = '${MAVEN_VERSION}'})
    - oneops.environmentCommitAndDeploy(platform = '${platform}', deployAllPlatforms = false)
 
  releaseDeploy:
    - exposeVars(maven)
    - call: release
    - var(RELEASE_VERSION = '%{MAVEN_VERSION.replace("-SNAPSHOT", "")}')
    - echo " Release Deploy to Oneops ${RELEASE_VERSION}"
    - oneops.transitionVariableUpdate(platform = '${platform}', component = artifact-app, variables = {artifactId = '${MAVEN_ARTIFACT_ID}', groupId='${MAVEN_GROUP_ID}' , appVersion = '${RELEASE_VERSION}'})
    - oneops.environmentCommitAndDeploy(platform = '${platform}', deployAllPlatforms = false)
